FROM python:3.9

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy app files
COPY app/ .

# ✅ Fix for Streamlit write permissions
ENV STREAMLIT_HOME=/app/.streamlit
RUN mkdir -p $STREAMLIT_HOME
COPY app/.streamlit/config.toml $STREAMLIT_HOME/config.toml

# Run the app
CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.enableCORS=false"]
